# Generated by Django 5.1.1 on 2025-07-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_is_deleted_chatmessage_is_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_edited',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
